version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:password@db:5432/whatsapp_simulator
      - PGUSER=postgres
      - PGHOST=db
      - PGPORT=5432
      - PGDATABASE=whatsapp_simulator
      - PGPASSWORD=password
    depends_on:
      - db
    restart: always
    
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=whatsapp_simulator
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres_data: